export const dossierContent = {
  dashboard: {
    title: "Tableau de bord",
    filterAll: "Toutes les démarches",
    filterMine: "Les miennes",
    empty: "Aucune démarche pour l'instant.",
    doneWindowCollapsed: "Vous avez traité l'essentiel de cette période.",
    unassigned: "Non assigné",
    benefitsLink: "Voir les aides potentielles",
    progressLabel: "Progression du dossier",
    progressValue: (percentage: number) => `${percentage} % des démarches traitées`,
    focusTitle: "À faire maintenant",
    focusEmpty: "Rien d'urgent en ce moment. Prenez le temps qu'il vous faut.",
    nextDeadlinePrefix: "Prochaine échéance :",
    // Never a countdown or a red badge: an overdue procedure is stated calmly.
    dueSoon: "À traiter cette semaine",
    dueLater: (date: string) => `À traiter avant le ${date}`,
    overdue: "À traiter dès que possible",
    noDueDate: "Sans échéance",
    commentsBadge: (count: number) => `${count} commentaire${count > 1 ? "s" : ""}`,
    forgottenMoneyLink: "Argent oublié",
    documentsLink: "Documents",
    membersLink: "Membres",
    activityLink: "Activité",
  },
  statusLabels: {
    todo: "À faire",
    in_progress: "En cours",
    waiting: "En attente",
    done: "Terminé",
    not_applicable: "Sans objet",
  },
  timeWindowLabels: {
    "24h": "Dans les 24 heures",
    "7d": "Dans les 7 jours",
    "30d": "Dans les 30 jours",
    "6m": "Dans les 6 mois",
  },
  procedureDetail: {
    tabs: {
      procedure: "Démarche",
      letter: "Courrier",
      comments: "Commentaires",
      history: "Historique",
    },
    statusLabel: "Statut",
    assigneeLabel: "Assigné à",
    organizationLabel: "Organisme",
    letter: {
      notice:
        "Ceci est un modèle à relire, compléter et signer par vos soins. Il ne s'agit pas d'un acte rédigé pour vous.",
      missingVariables: "Champs à compléter avant de générer le courrier :",
      downloadButton: "Télécharger en PDF",
      noTemplate: "Aucun modèle de courrier disponible pour cette démarche.",
      senderNameLabel: "Votre nom (signataire)",
    },
    comments: {
      placeholder: "Écrire un commentaire…",
      submitButton: "Publier",
      deleteButton: "Supprimer",
      deleted: "Commentaire supprimé",
      empty: "Aucun commentaire pour l'instant.",
      mentionLabel: "Mentionner",
      mentionPlaceholder: "Rechercher un membre…",
    },
    history: {
      empty: "Aucun événement pour l'instant.",
    },
    notFound: "Démarche introuvable.",
    tabsLabel: "Détail de la démarche",
  },
  benefits: {
    title: "Aides et prestations",
    empty: "Aucune aide identifiée pour ce profil.",
    formLink: "Accéder au formulaire officiel",
    amountPrefix: "Montant indicatif :",
    addButton: "Ajouter à mes démarches",
    alreadyAdded: "Déjà dans mes démarches",
  },
  forgottenMoney: {
    title: "Argent oublié",
    notice:
      "Ces services officiels sont gratuits. Nous ne prélevons aucune commission sur les sommes récupérées.",
    blockNotice: "Ce service officiel oriente vers l'organisme compétent, il ne s'y substitue pas.",
    officialLink: "Accéder au service officiel",
    addButton: "Ajouter à mes démarches",
    contractsTitle: "Contrats inventoriés à vérifier",
    contractsEmpty: "Aucun contrat n'a été inventorié pendant la préparation.",
    contractsIntro:
      "Ces contrats ont été notés pendant la préparation du dossier. Vérifiez auprès de chaque compagnie si un capital est dû.",
  },
  members: {
    title: "Membres et partage",
    roleLabels: {
      owner: "Titulaire",
      collaborator: "Collaborateur",
      viewer: "Lecteur",
      trusted_contact: "Contact de confiance",
    },
    invite: {
      title: "Inviter un membre",
      emailLabel: "Email",
      roleLabel: "Rôle",
      messageLabel: "Message personnel (optionnel)",
      emailPlaceholder: "membre@exemple.fr",
      submitButton: "Envoyer l'invitation",
      success: "Invitation envoyée.",
      linkNotice: "Lien d'invitation (à copier si l'email n'a pas pu être envoyé) :",
    },
    pending: {
      title: "Invitations en attente",
      empty: "Aucune invitation en attente.",
      expiresOn: "Expire le",
      revokeButton: "Révoquer",
    },
    selfSuffix: "(vous)",
    list: {
      title: "Membres",
      joinedOn: "Membre depuis le",
      removeButton: "Retirer",
      changeRoleTo: "Changer le rôle",
      transferButton: "Transférer la titularité",
      transferConfirmTitle: "Transférer la titularité ?",
      transferConfirmDescription:
        "Cette action est immédiate et irréversible : vous deviendrez collaborateur, cette personne deviendra titulaire.",
      transferConfirmButton: "Confirmer le transfert",
    },
  },
  activity: {
    title: "Activité",
    empty: "Aucun événement pour l'instant.",
    filterAllTypes: "Tous les types",
    filterAllMembers: "Tous les membres",
    filterTypeLabel: "Filtrer par type d'événement",
    filterMemberLabel: "Filtrer par membre",
    systemActor: "Le système",
    actionLabels: {
      status_changed: "a changé un statut",
      assignment_changed: "a changé une assignation",
      document_added: "a ajouté un document",
      document_removed: "a supprimé un document",
      member_invited: "a invité un membre",
      member_joined: "a rejoint le dossier",
      member_removed: "a retiré un membre",
      invitation_revoked: "a révoqué une invitation",
      ownership_transferred: "a transféré la titularité",
      dossier_activated: "a activé le dossier",
      letter_generated: "a généré un courrier",
      answers_updated: "a mis à jour les réponses",
      dossier_deleted: "a placé le dossier dans la corbeille",
    },
  },
  acceptInvitation: {
    title: "Rejoindre un dossier",
    loading: "Vérification de l'invitation…",
    invalidTitle: "Invitation invalide ou expirée",
    invalidDescription:
      "Ce lien n'est plus valable. Demandez à la personne titulaire de vous en envoyer un nouveau.",
    descriptionPrefix: "vous invite à rejoindre le dossier de",
    asRole: "en tant que",
    needAccount: "Créez un compte ou connectez-vous pour accepter cette invitation.",
    signupButton: "Créer un compte",
    loginButton: "Se connecter",
    acceptButton: "Accepter l'invitation",
    accepted: "Invitation acceptée !",
    goToDossier: "Accéder au dossier",
  },
  documents: {
    title: "Documents",
    notice:
      "Espace de stockage sécurisé et chiffré. Ce n'est pas un coffre-fort numérique à valeur probante.",
    uploadButton: "Ajouter un document",
    empty: "Aucun document pour l'instant.",
    downloadButton: "Télécharger",
    deleteButton: "Supprimer",
    addedBy: "ajouté par",
  },
  preparation: {
    title: "Préparer l'après",
    intro:
      "Prenez votre temps. Chaque élément rangé ici allège la tâche de vos proches, le moment venu.",
    progressLabel: "Éléments renseignés",
    blocks: {
      subject: {
        title: "Ma situation",
        description: "Vos informations personnelles et votre profil.",
      },
      contracts: {
        title: "Contrats et assurances",
        description: "Vos contrats d'assurance-vie, obsèques, mutuelle...",
      },
      documents: {
        title: "Documents importants",
        description: "Testament, livret de famille, titres de propriété...",
      },
      wishes: {
        title: "Souhaits et personnes à prévenir",
        description: "Vos volontés pour vos obsèques, les personnes à contacter.",
      },
      trustedContact: {
        title: "Contact de confiance",
        description: "La personne qui pourra signaler votre décès sur Sorento.",
      },
    },
    declareDeath: {
      button: "Signaler un décès",
      dialogTitle: "Signaler un décès sur ce dossier",
      dialogDescription:
        "Cette action active le dossier et le fait passer en suivi des démarches. Elle est immédiate et ne peut pas être annulée.",
      deathDateLabel: "Date du décès",
      confirmButton: "Confirmer et activer le dossier",
    },
  },
  subjectForm: {
    title: "Ma situation",
    identity: {
      firstNameLabel: "Prénom",
      lastNameLabel: "Nom",
    },
    profile: {
      title: "Mon profil",
      description:
        "Ces informations permettent d'identifier les démarches et aides qui vous concernent le moment venu.",
    },
    saveButton: "Enregistrer",
    saved: "Enregistré.",
  },
  contracts: {
    title: "Contrats et assurances",
    empty: "Aucun contrat renseigné pour l'instant.",
    addButton: "Ajouter un contrat",
    typeLabel: "Type de contrat",
    typePlaceholder: "Assurance-vie, obsèques, mutuelle...",
    companyLabel: "Organisme",
    contractNumberLabel: "Numéro de contrat (optionnel)",
    beneficiariesLabel: "Bénéficiaires connus (optionnel)",
    saveButton: "Enregistrer",
    cancelButton: "Annuler",
    editButton: "Modifier",
    deleteButton: "Supprimer",
  },
  wishes: {
    title: "Souhaits et personnes à prévenir",
    notice:
      "Ces informations n'ont pas de valeur légale. Pour organiser vos obsèques de façon contraignante, rapprochez-vous d'un notaire ou d'une entreprise de pompes funèbres habilitée.",
    funeralWishesLabel: "Souhaits concernant mes obsèques",
    peopleToNotifyLabel: "Personnes à prévenir",
    documentLocationLabel: "Où se trouvent mes documents importants",
    saveButton: "Enregistrer",
    saved: "Enregistré.",
  },
  trustedContact: {
    title: "Contact de confiance",
    notice:
      "Cette personne pourra, le moment venu, signaler votre décès et activer ce dossier pour vos proches. Choisissez quelqu'un en qui vous avez pleinement confiance.",
    empty: "Aucun contact de confiance désigné.",
    designateButton: "Désigner un contact de confiance",
    emailLabel: "Email",
    futureRoleLabel: "Rôle à l'activation",
    futureRoleOptions: {
      owner: "Titulaire",
      collaborator: "Collaborateur",
    },
    submitButton: "Envoyer la désignation",
    success: "Désignation envoyée. La personne recevra un email pour confirmer.",
    statusPending: "En attente de confirmation",
    statusConsented: "A confirmé son rôle",
    revokeButton: "Révoquer",
    revokeConfirmTitle: "Révoquer ce contact de confiance ?",
    revokeConfirmDescription:
      "Cette personne ne pourra plus signaler votre décès ni activer ce dossier.",
    revokeConfirmButton: "Confirmer la révocation",
  },
  activationPending: {
    title: "Activation en cours",
    description:
      "Un contact de confiance a signalé un décès pour ce dossier. Sauf opposition, il sera activé le",
    opposeButton: "Signaler un problème / m'opposer",
    opposeConfirmTitle: "Vous opposer à cette activation ?",
    opposeConfirmDescription:
      "L'activation sera suspendue et notre équipe sera notifiée pour vérifier la situation.",
    opposeConfirmButton: "Confirmer l'opposition",
    opposed: "Opposition enregistrée. L'activation est suspendue.",
  },
} as const;
