export const adminContent = {
  home: {
    title: "Administration",
    links: {
      catalog: "Référentiel",
      history: "Historique des modifications",
      testing: "Test de profil",
      metrics: "Statistiques",
    },
  },
  timeWindowLabels: {
    "24h": "Dans les 24 heures",
    "7d": "Dans les 7 jours",
    "30d": "Dans les 30 jours",
    "6m": "Dans les 6 mois",
  },
  catalog: {
    title: "Référentiel",
    tabs: {
      procedures: "Démarches",
      benefits: "Aides",
      conditions: "Conditions",
      letterTemplates: "Modèles de courrier",
    },
    addButton: "Ajouter",
    editButton: "Modifier",
    deleteButton: "Supprimer",
    saveButton: "Enregistrer",
    cancelButton: "Annuler",
    deleteConfirmTitle: "Supprimer cet élément du référentiel ?",
    deleteConfirmDescription: "Cette action est immédiate et irréversible.",
    deleteConfirmButton: "Confirmer la suppression",
    activeLabel: "Actif",
    inactiveLabel: "Inactif",
    procedures: {
      empty: "Aucune démarche dans le référentiel.",
      codeLabel: "Code",
      titleLabel: "Titre",
      descriptionLabel: "Description",
      organizationLabel: "Organisme",
      recipientAddressLabel: "Adresse du destinataire (optionnel)",
      timeWindowLabel: "Fenêtre temporelle",
      delayDaysLabel: "Délai (jours, optionnel)",
      referenceProfessionLabel: "Profession de référence (optionnel)",
      sourceUrlLabel: "URL source",
      lastVerifiedDateLabel: "Dernière vérification",
      activeLabel: "Actif dans le parcours",
    },
    benefits: {
      empty: "Aucune aide dans le référentiel.",
      codeLabel: "Code",
      titleLabel: "Titre",
      mainConditionLabel: "Condition principale",
      estimatedAmountLabel: "Montant estimé (optionnel)",
      organizationLabel: "Organisme",
      formUrlLabel: "URL du formulaire",
      cautionTextLabel: "Texte de prudence (affiché à l'utilisateur)",
      timeWindowLabel: "Fenêtre temporelle",
      sourceUrlLabel: "URL source",
      lastVerifiedDateLabel: "Dernière vérification",
      activeLabel: "Actif dans le parcours",
    },
    conditions: {
      empty: "Aucune condition dans le référentiel.",
      targetLabel: "Cible",
      targetProcedure: "Démarche",
      targetBenefit: "Aide",
      expressionLabel: "Expression (JSON)",
      expressionInvalid: "Expression JSON invalide.",
      expressionPlaceholder:
        '{"type":"comparison","field":"maritalStatus","operator":"eq","value":"married"}',
    },
    letterTemplates: {
      empty: "Aucun modèle de courrier dans le référentiel.",
      procedureLabel: "Démarche associée",
      titleLabel: "Titre",
      bodyTemplateLabel: "Corps du modèle",
      variablesLabel: "Variables (séparées par des virgules)",
      sourceUrlLabel: "URL source (optionnel)",
      lastVerifiedDateLabel: "Dernière vérification",
    },
  },
  history: {
    title: "Historique des modifications",
    empty: "Aucune modification enregistrée.",
    actionLabels: {
      created: "création",
      updated: "modification",
      deleted: "suppression",
    },
    tableLabels: {
      procedures: "démarche",
      benefits: "aide",
      conditions: "condition",
      letter_templates: "modèle de courrier",
    },
    systemActor: "système (initialisation)",
  },
  testing: {
    title: "Test de profil",
    notice:
      "Bac à sable interne : simule un profil et affiche le parcours résultant, sans créer de dossier.",
    deathDateLabel: "Date du décès simulée (optionnel, laisser vide pour le mode préparation)",
    resultTitle: "Résultat",
    proceduresTitle: "Démarches applicables",
    benefitsTitle: "Aides éligibles",
    noProcedures: "Aucune démarche applicable avec ce profil.",
    noBenefits: "Aucune aide éligible avec ce profil.",
  },
  metrics: {
    title: "Statistiques",
    notice:
      "Comptages agrégés et anonymisés uniquement. Aucun accès aux dossiers, suivis, commentaires ou documents.",
    totalUsers: "Utilisateurs",
    totalDossiers: "Dossiers",
    dossiersByStatus: "Dossiers par statut",
    activeTrustedContactDesignations: "Contacts de confiance actifs",
    trackingCompletionRatePercent: "Taux de complétion des démarches",
    activeCatalogProcedures: "Démarches actives au référentiel",
    activeCatalogBenefits: "Aides actives au référentiel",
    statusLabels: {
      PREPARATION: "Préparation",
      ACTIVE: "Actif",
    },
  },
} as const;
