export const adminContent = {
  home: {
    title: "Administration",
    links: {
      catalog: "Référentiel",
      history: "Historique des modifications",
      testing: "Test de profil",
      metrics: "Statistiques",
      designSystem: "Design system",
    },
  },
  designSystem: {
    title: "Design system",
    description:
      "Catalogue interne des fondations et composants partagés utilisés sur les pages publiques.",
    back: "Retour à l’administration",
    interactionHint:
      "Survolez les composants et parcourez-les au clavier pour vérifier leurs états interactifs.",
    sections: {
      colors: {
        title: "Couleurs sémantiques",
        description:
          "Les composants consomment ces rôles partagés, jamais une couleur propre à une page.",
      },
      typography: {
        title: "Typographie",
        description: "Une hiérarchie commune pour les titres, introductions et textes courants.",
        display: "Titre éditorial",
        heading: "Titre de section",
        body: "Texte courant lisible sur toutes les tailles d’écran.",
      },
      actions: {
        title: "Actions",
        description:
          "Le bouton du système couvre les actions applicatives. Le lien d’action partagé couvre la navigation publique.",
      },
      cards: {
        title: "Cartes",
        description: "Une même surface, déclinée par intentions visuelles typées.",
      },
      alerts: {
        title: "Messages",
        description: "Les statuts donnent une structure constante aux messages importants.",
      },
      icons: {
        title: "Icônes",
        description: "Un conteneur partagé garantit taille, centrage et contraste.",
      },
    },
    colors: [
      { id: "ink", label: "Texte principal" },
      { id: "cream", label: "Fond de page" },
      { id: "sage", label: "Surface douce" },
      { id: "leaf", label: "Action principale" },
      { id: "danger", label: "Danger" },
    ],
    actions: {
      primary: "Action principale",
      outline: "Action secondaire",
      ghost: "Action discrète",
      disabled: "Action indisponible",
      forward: "Continuer",
      back: "Revenir",
      light: "Action sur fond sombre",
    },
    cards: {
      surface: {
        title: "Surface",
        description: "Carte standard pour un contenu neutre.",
      },
      sage: {
        title: "Sauge",
        description: "Carte douce pour mettre un contenu en avant.",
      },
      inverse: {
        title: "Inversée",
        description: "Carte contrastée pour les sections sombres.",
      },
    },
    alerts: {
      default: "Information générale",
      success: "Opération réussie",
      warning: "Point d’attention",
      danger: "Action impossible",
    },
    iconLabel: "Repère visuel",
  },
  timeWindowLabels: {
    "24h": "Dans les 24 heures",
    "7d": "Dans les 7 jours",
    "30d": "Dans les 30 jours",
    "6m": "Dans les 6 mois",
  },
  catalog: {
    title: "Référentiel",
    tabs: {
      procedures: "Démarches",
      benefits: "Aides",
      conditions: "Conditions",
      letterTemplates: "Modèles de courrier",
    },
    addButton: "Ajouter",
    editButton: "Modifier",
    deleteButton: "Supprimer",
    saveButton: "Enregistrer",
    cancelButton: "Annuler",
    deleteConfirmTitle: "Supprimer cet élément du référentiel ?",
    deleteConfirmDescription: "Cette action est immédiate et irréversible.",
    deleteConfirmButton: "Confirmer la suppression",
    activeLabel: "Actif",
    inactiveLabel: "Inactif",
    procedures: {
      empty: "Aucune démarche dans le référentiel.",
      codeLabel: "Code",
      titleLabel: "Titre",
      descriptionLabel: "Description",
      organizationLabel: "Organisme",
      recipientAddressLabel: "Adresse du destinataire (optionnel)",
      timeWindowLabel: "Fenêtre temporelle",
      delayDaysLabel: "Délai (jours, optionnel)",
      referenceProfessionLabel: "Profession de référence (optionnel)",
      sourceUrlLabel: "URL source",
      lastVerifiedDateLabel: "Dernière vérification",
      activeLabel: "Actif dans le parcours",
    },
    benefits: {
      empty: "Aucune aide dans le référentiel.",
      codeLabel: "Code",
      titleLabel: "Titre",
      mainConditionLabel: "Condition principale",
      estimatedAmountLabel: "Montant estimé (optionnel)",
      organizationLabel: "Organisme",
      formUrlLabel: "URL du formulaire",
      cautionTextLabel: "Texte de prudence (affiché à l'utilisateur)",
      timeWindowLabel: "Fenêtre temporelle",
      sourceUrlLabel: "URL source",
      lastVerifiedDateLabel: "Dernière vérification",
      activeLabel: "Actif dans le parcours",
    },
    conditions: {
      empty: "Aucune condition dans le référentiel.",
      targetLabel: "Cible",
      targetProcedure: "Démarche",
      targetBenefit: "Aide",
      expressionLabel: "Expression (JSON)",
      expressionInvalid: "Expression JSON invalide.",
      expressionPlaceholder:
        '{"type":"comparison","field":"maritalStatus","operator":"eq","value":"married"}',
    },
    letterTemplates: {
      empty: "Aucun modèle de courrier dans le référentiel.",
      procedureLabel: "Démarche associée",
      titleLabel: "Titre",
      bodyTemplateLabel: "Corps du modèle",
      variablesLabel: "Variables (séparées par des virgules)",
      sourceUrlLabel: "URL source (optionnel)",
      lastVerifiedDateLabel: "Dernière vérification",
    },
  },
  history: {
    title: "Historique des modifications",
    empty: "Aucune modification enregistrée.",
    actionLabels: {
      created: "création",
      updated: "modification",
      deleted: "suppression",
    },
    tableLabels: {
      procedures: "démarche",
      benefits: "aide",
      conditions: "condition",
      letter_templates: "modèle de courrier",
    },
    systemActor: "système (initialisation)",
  },
  testing: {
    title: "Test de profil",
    notice:
      "Bac à sable interne : simule un profil et affiche le parcours résultant, sans créer de dossier.",
    deathDateLabel: "Date du décès simulée (optionnel, laisser vide pour le mode préparation)",
    resultTitle: "Résultat",
    proceduresTitle: "Démarches applicables",
    benefitsTitle: "Aides éligibles",
    noProcedures: "Aucune démarche applicable avec ce profil.",
    noBenefits: "Aucune aide éligible avec ce profil.",
  },
  metrics: {
    title: "Statistiques",
    notice:
      "Comptages agrégés et anonymisés uniquement. Aucun accès aux dossiers, suivis, commentaires ou documents.",
    totalUsers: "Utilisateurs",
    totalDossiers: "Dossiers",
    dossiersByStatus: "Dossiers par statut",
    activeTrustedContactDesignations: "Contacts de confiance actifs",
    trackingCompletionRatePercent: "Taux de complétion des démarches",
    activeCatalogProcedures: "Démarches actives au référentiel",
    activeCatalogBenefits: "Aides actives au référentiel",
    statusLabels: {
      PREPARATION: "Préparation",
      ACTIVE: "Actif",
    },
  },
} as const;
